In [3]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import matplotlib.pyplot as plt

In [4]:
partone = pd.read_csv(r'c:\Users\lengo\Downloads\development data\gear_target_vs_actual_1996_2000 (1).csv')
partone

            indicator  year  gear_target  actual_to_1999 scan_reconstructed
0     deficit_pct_gdp  1996          5.1             4.9                  R
1     deficit_pct_gdp  1997          4.0             4.6                NaN
2     deficit_pct_gdp  1998          3.5             3.3                  R
3     deficit_pct_gdp  1999          3.0             2.6                NaN
4     deficit_pct_gdp  2000          3.0             NaN                NaN
..                ...   ...          ...             ...                ...
70  inflation_cpi_pct  1996          8.4             7.4                NaN
71  inflation_cpi_pct  1997         10.9             8.6                NaN
72  inflation_cpi_pct  1998          9.6             6.9                NaN
73  inflation_cpi_pct  1999          7.7             5.2                NaN
74  inflation_cpi_pct  2000          NaN             NaN                NaN

[75 rows x 5 columns]

In [16]:
#Colapse the two value columns into one value column plus a metric label
table1 = partone.melt(id_vars=['indicator', 'year'], value_vars=['gear_target', 'actual_to_1999'],
var_name='metric', value_name='value')

In [17]:
#Making the table wide
table_wide = table1.pivot(index=['metric', 'indicator'], columns='year', values='value')
table_wide = table_wide.reindex(["gear_target", "actual_to_1999"], level="metric")
table_wide

year                                                  1996  1997  1998  1999  \
metric         indicator
gear_target    current_account_deficit_pct_gdp         2.2   2.0   2.2   2.5
               deficit_pct_gdp                         5.1   4.0   3.5   3.0
               govt_dissaving_pct_gdp                  3.1   2.3   1.7   0.7
               inflation_cpi_pct                       8.4  10.9   9.6   7.7
               nonagric_formal_employment_growth_pct   1.3   3.0   2.7   3.5
               real_bank_rate_pct                      7.0   5.0   4.0   3.0
               real_gdp_growth_pct                     3.5   2.9   3.8   4.9
               real_govt_consumption_pct_gdp          19.1  19.5  19.0  18.5
               real_govt_investment_growth_pct         3.4   2.7   6.4   7.5
               real_mfg_export_growth_pct             10.3  12.2   8.3  10.5
               real_nongold_export_growth_pct          9.1   8.0   7.0   7.8
               real_parastatal_investment_growth_pct   3.0   5.0  10.0  10.0
               real_private_investment_growth_pct      9.3   9.1   9.3  13.9
               real_wage_growth_private_pct            0.5   1.0   1.0   1.0
               reer_change_pct                        -8.5  -0.3   0.0   0.0
actual_to_1999 current_account_deficit_pct_gdp         NaN   NaN   NaN   NaN
               deficit_pct_gdp                         4.9   4.6   3.3   2.6
               govt_dissaving_pct_gdp                  NaN   NaN   NaN   NaN
               inflation_cpi_pct                       7.4   8.6   6.9   5.2
               nonagric_formal_employment_growth_pct  -0.7  -1.7  -3.7  -3.2
               real_bank_rate_pct                      8.8   7.4   8.1   7.3
               real_gdp_growth_pct                     4.2   2.5   0.6   1.2
               real_govt_consumption_pct_gdp           NaN   NaN   NaN   NaN
               real_govt_investment_growth_pct         NaN   NaN   NaN   NaN
               real_mfg_export_growth_pct              NaN   NaN   NaN   NaN
               real_nongold_export_growth_pct          NaN   NaN   NaN   NaN
               real_parastatal_investment_growth_pct   NaN   NaN   NaN   NaN
               real_private_investment_growth_pct      6.1   4.7  -2.9  -4.4
               real_wage_growth_private_pct            1.7   2.3   8.6   3.0
               reer_change_pct                        -6.3   6.4  -9.2   NaN

year                                                  2000
metric         indicator
gear_target    current_account_deficit_pct_gdp         3.1
               deficit_pct_gdp                         3.0
               govt_dissaving_pct_gdp                  0.6
               inflation_cpi_pct                       NaN
               nonagric_formal_employment_growth_pct   4.3
               real_bank_rate_pct                      3.0
               real_gdp_growth_pct                     6.1
               real_govt_consumption_pct_gdp          18.1
               real_govt_investment_growth_pct        16.7
               real_mfg_export_growth_pct             12.8
               real_nongold_export_growth_pct         10.2
               real_parastatal_investment_growth_pct  10.0
               real_private_investment_growth_pct     17.0
               real_wage_growth_private_pct            1.0
               reer_change_pct                         0.0
actual_to_1999 current_account_deficit_pct_gdp         NaN
               deficit_pct_gdp                         NaN
               govt_dissaving_pct_gdp                  NaN
               inflation_cpi_pct                       NaN
               nonagric_formal_employment_growth_pct   NaN
               real_bank_rate_pct                      NaN
               real_gdp_growth_pct                     NaN
               real_govt_consumption_pct_gdp           NaN
               real_govt_investment_growth_pct         NaN
               real_mfg_export_growth_pct              NaN
               real_nongold_export_growth_pct          NaN
               real_parastatal_investment_growth_pct   NaN
               real_private_investment_growth_pct      NaN
               real_wage_growth_private_pct            NaN
               reer_change_pct                         NaN

In [18]:
#Removing the 2000 column
table_wide= table_wide.drop(columns=2000)
table_wide

year                                                  1996  1997  1998  1999
metric         indicator
gear_target    current_account_deficit_pct_gdp         2.2   2.0   2.2   2.5
               deficit_pct_gdp                         5.1   4.0   3.5   3.0
               govt_dissaving_pct_gdp                  3.1   2.3   1.7   0.7
               inflation_cpi_pct                       8.4  10.9   9.6   7.7
               nonagric_formal_employment_growth_pct   1.3   3.0   2.7   3.5
               real_bank_rate_pct                      7.0   5.0   4.0   3.0
               real_gdp_growth_pct                     3.5   2.9   3.8   4.9
               real_govt_consumption_pct_gdp          19.1  19.5  19.0  18.5
               real_govt_investment_growth_pct         3.4   2.7   6.4   7.5
               real_mfg_export_growth_pct             10.3  12.2   8.3  10.5
               real_nongold_export_growth_pct          9.1   8.0   7.0   7.8
               real_parastatal_investment_growth_pct   3.0   5.0  10.0  10.0
               real_private_investment_growth_pct      9.3   9.1   9.3  13.9
               real_wage_growth_private_pct            0.5   1.0   1.0   1.0
               reer_change_pct                        -8.5  -0.3   0.0   0.0
actual_to_1999 current_account_deficit_pct_gdp         NaN   NaN   NaN   NaN
               deficit_pct_gdp                         4.9   4.6   3.3   2.6
               govt_dissaving_pct_gdp                  NaN   NaN   NaN   NaN
               inflation_cpi_pct                       7.4   8.6   6.9   5.2
               nonagric_formal_employment_growth_pct  -0.7  -1.7  -3.7  -3.2
               real_bank_rate_pct                      8.8   7.4   8.1   7.3
               real_gdp_growth_pct                     4.2   2.5   0.6   1.2
               real_govt_consumption_pct_gdp           NaN   NaN   NaN   NaN
               real_govt_investment_growth_pct         NaN   NaN   NaN   NaN
               real_mfg_export_growth_pct              NaN   NaN   NaN   NaN
               real_nongold_export_growth_pct          NaN   NaN   NaN   NaN
               real_parastatal_investment_growth_pct   NaN   NaN   NaN   NaN
               real_private_investment_growth_pct      6.1   4.7  -2.9  -4.4
               real_wage_growth_private_pct            1.7   2.3   8.6   3.0
               reer_change_pct                        -6.3   6.4  -9.2   NaN

In [24]:
#Deleting the extra indicators
#Indicators to filter on
ind = ['real_gdp_growth_pct', 'real_private_investment_growth_pct', 'inflation_cpi_pct','nonagric_formal_employment_growth_pct','real_bank_rate_pct','real_bank_rate_pct', 'deficit_pct_gdp' ]

idx= pd.IndexSlice
subset = table_wide.loc[idx[:, ind], :]
subset

year                                                  1996  1997  1998  1999
metric         indicator
gear_target    real_gdp_growth_pct                     3.5   2.9   3.8   4.9
actual_to_1999 real_gdp_growth_pct                     4.2   2.5   0.6   1.2
gear_target    real_private_investment_growth_pct      9.3   9.1   9.3  13.9
actual_to_1999 real_private_investment_growth_pct      6.1   4.7  -2.9  -4.4
gear_target    inflation_cpi_pct                       8.4  10.9   9.6   7.7
actual_to_1999 inflation_cpi_pct                       7.4   8.6   6.9   5.2
gear_target    nonagric_formal_employment_growth_pct   1.3   3.0   2.7   3.5
actual_to_1999 nonagric_formal_employment_growth_pct  -0.7  -1.7  -3.7  -3.2
gear_target    real_bank_rate_pct                      7.0   5.0   4.0   3.0
actual_to_1999 real_bank_rate_pct                      8.8   7.4   8.1   7.3
gear_target    deficit_pct_gdp                         5.1   4.0   3.5   3.0
actual_to_1999 deficit_pct_gdp                         4.9   4.6   3.3   2.6